name: Android CI

on:
  push:
    branches:
      - master  # or your primary branch name
  pull_request:
    branches:
      - master  # or your primary branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'  # Adjust Java version if needed

    - name: Grant execute permission for Gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle
      run: ./gradlew assembleDebug  # Adjust task as needed for your build

    - name: Upload APK artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-debug
        path: app/build/outputs/apk/debug/app-debug.apk  # Adjust path to your APK
